apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
spec:
  replicas: 2
  selector:
    matchExpressions:
        - {key: myname, operator: In, values: [sanjay, sanju, sanja]}
        - {key: myname, operator: NotIn, values: [production]}
  template:
    metadata:
      name: sanja
      labels:
        myname: sanjay
    spec:
      containers:
        - name: co1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo my first cont ; sleep 5; done"]
